LOGIN = "login"
LOGOUT = "logout"
LOGIN_FAILED = "login_failed"
ACCOUNT_LOCKED = "account_locked"
CHANGE_PASSWORD = "change_password"

USER_CREATED = "user_created"
USER_UPDATED = "user_updated"
USER_DELETED = "user_deleted"
USER_PASSWORD_RESET = "user_password_reset"
USER_TOGGLED_ACTIVE = "user_toggled_active"
SESSION_KILLED_BY_ADMIN = "session_killed_by_admin"
USERNAME_CHANGED = "username_changed"
AVATAR_UPDATED = "avatar_updated"
AVATAR_REMOVED = "avatar_removed"
